### ISSUE TITLE
Station UU.NMU Makes No Detections When It Should

### ISSUE THREAD

**Issue by chasebatch** [d-chambers/Detex#14]
UU.NMU is a close station  (~30km) to my swarm of interest with good template event waveforms. However, it is making no detections even though it looks like there are good detections to be made that were detected by my other 3 stations, UU.MSU, UU.IMU, UU.DWU. 

Here is an example of a detection UU.NMU is missing.
![2003-11-28t16-48-00](https://cloud.githubusercontent.com/assets/15195673/11222479/ddaec404-8d27-11e5-807d-3d0a990ac994.png)

I have tried running just the vertical component in case there was an issue running one 3-component station with single component stations, but again no detections. Any thoughts on why this would be happening? It would be useful for me and others to be able to utilize this station.

**Comment by d-chambers** [comment]
There is a feature to probe times of interest and look at the detection statistics as well as loaded continuous data. If you attach your station key and template key, or email them to me, and I will show you how to use this feature (and make sure it works on your data). My guess is that the continuous data are getting rejected, or that the event isn't quite similar enough to trigger a detection. Sometimes this can happen on stations that are "too close" (consider figure 6 of the GJI publication where some detections are made on the farther station but not the closer one).

**Comment by d-chambers** [comment]
If you cant upload them to this post try changing the extension to .txt rather than .csv

**Comment by chasebatch** [comment]
[StationKey.txt](https://github.com/d-chambers/Detex/files/39139/StationKey.txt)
[TemplateKey.txt](https://github.com/d-chambers/Detex/files/39141/TemplateKey.txt)

**Comment by d-chambers** [comment]
Ok I am not 100% sure what the issue here was, but when I run the detections from the latest develop branch (v1.0.3b) this event is detected on IMU, infact it has the highest detection statistic of all the stations. I made some rather large changes to detex on the develop branch. It should be much more robust and reject less data based on gaps, etc. so I imagine the older version of detex is rejecting that chunk of continuous data for some reason. I have attached the csv to show you what I mean.

If you want to try the develop branch version of detex it "should" work for you, but I am still doing some testing on it. I will try to have it merged back into the master branch soon, I just need to run a few more tests on it.

Standby on the probe continuous data feature, I am making an advanced tutorial that will go into details on that. Should have it up in a few weeks, hopefully, but I will update what progress I have made so far on it to the advanced_tutorial branch. As always, if you have any feedback or suggestions let me know. 

[2003-11-28T16-48-30detections.txt](https://github.com/d-chambers/Detex/files/39640/2003-11-28T16-48-30detections.txt)
